/**
 * @tollway/express
 *
 * Drop-in Express middleware for x402 monetization on Stellar.
 *
 * Usage:
 *   import { tollway } from "@tollway/express";
 *   app.use(tollway(config));
 *
 * This middleware:
 *   1. Parses the Tollway config
 *   2. For each incoming request, resolves the pricing decision
 *   3. If the route has a free tier and the caller hasn't exhausted it, passes through
 *   4. If payment is required, delegates to @x402/express middleware
 *   5. Emits analytics events for every request
 */

import {
  parseConfig,
  resolvePrice,
  createQuotaTracker,
  createAnalytics,
} from "@tollway/core";

/**
 * Create the Tollway Express middleware.
 *
 * @param {object} rawConfig — the developer's tollway.config export
 * @returns {function} Express middleware
 */
export function tollway(rawConfig) {
  const config = parseConfig(rawConfig);
  const quota = createQuotaTracker(config.freeTier);
  const analytics = createAnalytics(config.analytics);

  // Lazy-load the x402 facilitator client for payment verification.
  // The 402 challenge is generated by Tollway directly (no facilitator needed).
  // The facilitator is only contacted to verify/settle actual payment proofs.
  let facilitatorClient = null;
  let stellarScheme = null;

  async function ensureFacilitatorLoaded() {
    if (facilitatorClient) return;
    try {
      const { HTTPFacilitatorClient } = await import("@x402/core/server");
      const { ExactStellarScheme } = await import("@x402/stellar/exact/server");

      facilitatorClient = new HTTPFacilitatorClient({
        url: config.facilitatorUrl,
      });
      stellarScheme = new ExactStellarScheme();
    } catch (err) {
      console.error(
        "[Tollway] Failed to load x402 dependencies. Install them:\n" +
          "  npm install @x402/core @x402/express @x402/stellar\n",
        err.message
      );
      throw err;
    }
  }

  // Return the middleware function
  return async function tollwayMiddleware(req, res, next) {
    const method = req.method;
    const path = req.path || req.url;

    // Resolve what this route should cost
    const decision = await resolvePrice(config, {
      method,
      path,
      req,
    });

    // Unpriced routes pass through untouched
    if (decision.action === "unpriced") {
      analytics.emit("request.unpriced", { route: `${method} ${path}` });
      return next();
    }

    // Free routes always pass through
    if (decision.action === "free") {
      analytics.emit("request.free", { route: `${method} ${path}` });
      return next();
    }

    // Paid route — check free tier first
    if (config.freeTier.enabled) {
      const reqInfo = {
        ip: req.ip || req.socket?.remoteAddress,
        walletAddress: extractWalletAddress(req),
        headers: req.headers,
      };

      const quotaResult = await quota.check(reqInfo);

      if (quotaResult.allowed) {
        // Free tier still has capacity — serve for free and record usage
        await quota.record(reqInfo);
        analytics.emit("request.free", {
          route: `${method} ${path}`,
          caller: quota.identifyCaller(reqInfo),
          remaining: quotaResult.remaining - 1,
        });

        // Attach tollway context to req for the developer's handler
        req.tollway = {
          paid: false,
          freeTier: true,
          remaining: quotaResult.remaining - 1,
        };

        return next();
      }

      // Free tier exhausted — fall through to x402 payment
      analytics.emit("request.blocked", {
        route: `${method} ${path}`,
        caller: quota.identifyCaller(reqInfo),
        priceUsd: decision.priceUsd,
      });
    }

    // Payment required — check for payment proof header
    const paymentHeader =
      req.headers["payment-signature"] || req.headers["x-payment"];

    if (!paymentHeader) {
      // No payment proof — return 402 with payment instructions
      const paymentRequired = {
        x402Version: 1,
        accepts: {
          scheme: "exact",
          price: `$${decision.priceUsd}`,
          network: config.network,
          payTo: config.payTo,
        },
        description: decision.description,
        resource: `${method} ${path}`,
      };

      res.status(402);
      res.set("X-Payment-Required", JSON.stringify(paymentRequired));
      res.json(paymentRequired);
      return;
    }

    // Payment proof present — verify via the x402 facilitator
    try {
      await ensureFacilitatorLoaded();

      const verification = await facilitatorClient.verify(paymentHeader, {
        scheme: "exact",
        price: `$${decision.priceUsd}`,
        network: config.network,
        payTo: config.payTo,
      });

      if (!verification?.valid) {
        analytics.emit("payment.failed", {
          route: `${method} ${path}`,
          reason: "verification_failed",
        });
        res.status(402).json({
          error: "Payment verification failed",
          x402: {
            scheme: "exact",
            price: `$${decision.priceUsd}`,
            network: config.network,
            payTo: config.payTo,
          },
        });
        return;
      }

      // Payment verified — settle and proceed
      facilitatorClient
        .settle(paymentHeader, {
          scheme: "exact",
          price: `$${decision.priceUsd}`,
          network: config.network,
          payTo: config.payTo,
        })
        .then(() => {
          analytics.emit("payment.settled", {
            route: `${method} ${path}`,
            priceUsd: decision.priceUsd,
          });
        })
        .catch((err) => {
          analytics.emit("payment.failed", {
            route: `${method} ${path}`,
            reason: err.message,
          });
        });

      req.tollway = {
        paid: true,
        freeTier: false,
        priceUsd: decision.priceUsd,
        route: decision.matchedRoute,
      };
      analytics.emit("request.paid", {
        route: `${method} ${path}`,
        priceUsd: decision.priceUsd,
      });
      return next();
    } catch (err) {
      console.error("[Tollway] Payment verification error:", err.message);
      res.status(500).json({ error: "Payment processing error" });
    }
  };
}

/**
 * Try to extract a wallet address from an x402 payment header.
 * Used for quota identification when identifyBy === "wallet".
 */
function extractWalletAddress(req) {
  // x402 v2 puts the payment payload in the PAYMENT-SIGNATURE header.
  // The wallet address is embedded in the signed auth entry.
  // For free-tier tracking we just need a stable identifier —
  // we can extract it from the base64-decoded payload if present.
  const paymentHeader =
    req.headers["payment-signature"] ||
    req.headers["x-payment"] ||
    req.headers["x-402-payment"];

  if (!paymentHeader) return null;

  try {
    // The payment header is base64-encoded JSON with a payload.authorization
    // that contains the signer's address. This is a best-effort extraction.
    const decoded = JSON.parse(
      Buffer.from(paymentHeader, "base64").toString("utf-8")
    );
    return decoded?.payload?.authorization?.from ||
           decoded?.payload?.signer ||
           decoded?.from ||
           null;
  } catch {
    return null;
  }
}

export default tollway;
